spring:
  h2:
    console:
      path: /h2
      enabled: true
      settings:
        trace: false
        web-allow-others: true
  datasource:
    url: jdbc:h2:tcp://localhost:9092/./equipment;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: admin
    password: 1234
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
        show_sql: true
  servlet:
    multipart:
      max-file-size: 1024KB
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger
server:
  servlet:
    context-path: /v1
