spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    url: jdbc:h2:mem:equipment
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger
server:
  servlet:
    context-path: /v1
